apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-health-check-61a7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-health-check-61a7
    app.kubernetes.io/part-of: e2e-nodejs
  name: nodejs-health-check-61a7
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-health-check-61a7
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-health-check-61a7
    spec:
      containers:
      - image: quay.io/bootstrap/rhtap-demo-tlpw-tenant/e2e-nodejs/nodejs-health-check-61a7@sha256:b6a2f9a6d0b311e35a1fd20d9029e91bdfa4bbf2dfd13dba2ff5b5a45ea5599b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
